import fs from 'fs';

const dogProducts = [
  {
    id: "dog-dry-food-1",
    name: { EN: "Royal Canin Size Health Nutrition Medium Adult Dry Dog Food", TR: "Royal Canin Medium Yetişkin Kuru Köpek Maması" },
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400",
    price: 1350.00,
    oldPrice: 1550.00,
    discount: 15,
    rating: 4.8,
    reviews: 1250,
    sold: 3400,
    stock: 120,
    badges: ["Bestseller"],
    brand: "Royal Canin",
    flavor: "Chicken",
    weight: "15kg",
    age: "Adult",
    breedSize: "Medium",
    _categoryId: "dogs",
    _subCategoryId: "dog-dry-food",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  },
  {
    id: "dog-dry-food-2",
    name: { EN: "Acana Grain-Free Adult Dog Food", TR: "Acana Tahılsız Yetişkin Köpek Maması" },
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400",
    price: 1850.00,
    rating: 4.9,
    reviews: 420,
    sold: 1500,
    stock: 45,
    badges: ["Premium"],
    brand: "Acana",
    flavor: "Lamb & Apple",
    weight: "11.4kg",
    age: "Adult",
    breedSize: "All Sizes",
    _categoryId: "dogs",
    _subCategoryId: "dog-dry-food",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  },
  {
    id: "dog-wet-food-1",
    name: { EN: "Pro Plan NutriSavour Adult Wet Dog Food", TR: "Pro Plan NutriSavour Yetişkin Yaş Köpek Maması" },
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400",
    price: 65.00,
    oldPrice: 80.00,
    discount: 18,
    rating: 4.7,
    reviews: 210,
    sold: 5000,
    stock: 350,
    badges: [],
    brand: "Pro Plan",
    flavor: "Beef",
    weight: "100g",
    age: "Adult",
    breedSize: "All Sizes",
    _categoryId: "dogs",
    _subCategoryId: "dog-wet-food",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  },
  {
    id: "dog-treats-1",
    name: { EN: "Pedigree Dentastix Daily Dental Chews", TR: "Pedigree Dentastix Günlük Ağız Bakım Çubuğu" },
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400",
    price: 125.00,
    rating: 4.8,
    reviews: 500,
    sold: 12000,
    stock: 500,
    badges: ["Bestseller"],
    brand: "Pedigree",
    flavor: "Original",
    weight: "7 Sticks",
    age: "Adult",
    breedSize: "Large",
    _categoryId: "dogs",
    _subCategoryId: "dog-treats",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  },
  {
    id: "dog-toys-1",
    name: { EN: "Kong Classic Interactive Chew Dog Toy", TR: "Kong Classic İnteraktif Çiğneme Köpek Oyuncağı" },
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400",
    price: 350.00,
    rating: 4.9,
    reviews: 3200,
    sold: 8000,
    stock: 150,
    badges: ["Bestseller", "Durable"],
    brand: "KONG",
    material: "Natural Rubber",
    color: "Red",
    breedSize: "Large",
    _categoryId: "dogs",
    _subCategoryId: "dog-toys",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  },
  {
    id: "dog-collars-1",
    name: { EN: "Julius-K9 IDC Powerharness Chest Harness", TR: "Julius-K9 IDC Powerharness Göğüs Tasması" },
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400",
    price: 1100.00,
    oldPrice: 1350.00,
    discount: 18,
    rating: 4.8,
    reviews: 950,
    sold: 2100,
    stock: 80,
    badges: ["Premium"],
    brand: "Julius-K9",
    color: "Black",
    breedSize: "Large",
    _categoryId: "dogs",
    _subCategoryId: "dog-collars",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  },
  {
    id: "dog-clothing-1",
    name: { EN: "Waterproof Reflective Dog Raincoat", TR: "Su Geçirmez Reflektörlü Köpek Yağmurluğu" },
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400",
    price: 450.00,
    rating: 4.7,
    reviews: 120,
    sold: 450,
    stock: 60,
    badges: ["New"],
    brand: "PetWear",
    material: "Polyester",
    color: "Yellow",
    breedSize: "Medium",
    _categoryId: "dogs",
    _subCategoryId: "dog-clothing",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  },
  {
    id: "dog-clothing-2",
    name: { EN: "Warm Knitted Dog Winter Sweater", TR: "Sıcak Tutan Örgü Köpek Kışlık Kazağı" },
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400",
    price: 320.00,
    oldPrice: 400.00,
    discount: 20,
    rating: 4.8,
    reviews: 80,
    sold: 300,
    stock: 45,
    badges: [],
    brand: "PetWear",
    material: "Acrylic Yarn",
    color: "Navy Blue",
    breedSize: "Small",
    _categoryId: "dogs",
    _subCategoryId: "dog-clothing",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  },
  {
    id: "dog-beds-1",
    name: { EN: "Orthopedic Memory Foam Dog Bed", TR: "Ortopedik Hafızalı Sünger Köpek Yatağı" },
    image: "https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?q=80&w=800",
    price: 1450.00,
    rating: 4.9,
    reviews: 350,
    sold: 800,
    stock: 30,
    badges: ["Premium", "Comfort"],
    brand: "SleepyPet",
    material: "Memory Foam",
    color: "Grey",
    breedSize: "Large",
    _categoryId: "dogs",
    _subCategoryId: "dog-beds",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  },
  {
    id: "dog-shampoo-1",
    name: { EN: "Beaphar Macadamia Oil Sensitive Dog Shampoo", TR: "Beaphar Macadamia Yağlı Hassas Köpek Şampuanı" },
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400",
    price: 250.00,
    rating: 4.6,
    reviews: 180,
    sold: 1100,
    stock: 200,
    badges: [],
    brand: "Beaphar",
    weight: "250ml",
    _categoryId: "dogs",
    _subCategoryId: "dog-shampoo",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  },
  {
    id: "dog-vitamins-1",
    name: { EN: "GimDog Multivitamin Paste for Dogs", TR: "GimDog Köpekler İçin Multivitamin Macunu" },
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400",
    price: 195.00,
    rating: 4.7,
    reviews: 240,
    sold: 1500,
    stock: 140,
    badges: ["Health"],
    brand: "GimDog",
    weight: "50g",
    age: "All Ages",
    _categoryId: "dogs",
    _subCategoryId: "dog-vitamins",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  },
  {
    id: "dog-carriers-1",
    name: { EN: "Airline Approved Pet Carrier Bag", TR: "Uçuş Onaylı Evcil Hayvan Taşıma Çantası" },
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400",
    price: 850.00,
    oldPrice: 1000.00,
    discount: 15,
    rating: 4.8,
    reviews: 115,
    sold: 450,
    stock: 25,
    badges: ["Travel", "Safe"],
    brand: "TravelPet",
    material: "Nylon",
    color: "Black",
    breedSize: "Small",
    _categoryId: "dogs",
    _subCategoryId: "dog-carriers",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  },
  {
    id: "dog-bowls-1",
    name: { EN: "Anti-Slip Stainless Steel Dog Bowl", TR: "Kaymaz Tabanlı Paslanmaz Çelik Köpek Mama Kabı" },
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400",
    price: 180.00,
    rating: 4.7,
    reviews: 320,
    sold: 2100,
    stock: 180,
    badges: [],
    brand: "BasicPet",
    material: "Stainless Steel",
    weight: "750ml",
    _categoryId: "dogs",
    _subCategoryId: "dog-bowls",
    _categoryLabel: { EN: "Dogs", TR: "Köpekler" }
  }
];

const content = `import { ProductWithCategory } from './productGenerator';

export const DOG_PRODUCTS: ProductWithCategory[] = ${JSON.stringify(dogProducts, null, 2)};
`;

fs.writeFileSync('./src/products_dog.ts', content);
if (fs.existsSync('./src/products_dog.ts.tsx')) {
  fs.rmSync('./src/products_dog.ts.tsx', { force: true });
}
console.log('Generated nicely formatted DOG_PRODUCTS array.');
